### PR TITLE
[F] Refactor btree & comparative predicates. 

### PR DESCRIPTION
**Pull request by Istar-Eldritch**
Adds the following features:
@DennisSchwartz Any comments on the syntax?

| Function | Syntax |
|:---|:----:|
| Range match | ~_`predicate:val1..val2`_~
| Equal (implicit if not defined) | _`predicate:=val`_
| Greater than  | _`predicate:>val`_
| Less than  | _`predicate:<val`_
| Greater or equal than  | _`predicate:>=val`_ / ~_`predicate:val..`_~
| Less or equal than |  _`predicate:<val`_ / ~_`predicate:..val`_~
| Predicate exists | _`predicate:*`_
| Predicate starts with | _`predicate:startswi*`_
| Exact match | _`predicate:==val`_

Ranges with the syntax x..y wont be implemented in this iteration because of some issues parsing decimal numbers. Instead something like `predicate:<v1 predicate:>v2` can be used meanwhile.

### CODE REVIEW

**Comment by DennisSchwartz** [comment]
@istar: Looks great!
Some comments:
Do you think the range will work with decimal numbers? I.e. `1.2..1.4`
And I assume `val` can still be quoted? 
So when I want to search for exactly Transcription Profiling in assay I can do:
`assay:=="Transcription Profiling"`?
Those would be great if they work this way.

One more thing: How are the wildcards working? Just for the ranges and `exists` filter or would it also work as `assay:Transcription*` ?

**Comment by Istar-Eldritch** [comment]
You brought a good point with the decimal numbers in the ranges and they add some complexity I do not want to deal with now. Because of this ranges with `x..y` wont be implemented in this iteration, even if integer and string values would work fine it would create confusion if someone tries a decimal value.

Regarding the exact match, yes, it works as you expect.

Wildcards won't be real wildcards but something that emulates their functionality without the performance costs. `predicate:*` will check that the predicate exists in the object. `predicate: some*` will check that the predicated value starts with the string. Wildcards like `predicate:*thing` or `predicate: so*thing` wont be supported.

This should cover the majority of the use cases and won't compromise performance.

**Comment by DennisSchwartz** [comment]
That's great. Good work on this :) Went much faster than I thought it might haha. I remember it was a bit of a thing when we tried this the first time.

**Comment by Istar-Eldritch** [comment]
This is done and it should be stable now. Integrations have been done in both the [api](https://github.com/repositive/api.repositive.io/pull/238) and the [discover frontend](https://github.com/repositive/discover.repositive.io/pull/903) this integrations have a hard block on this PR.

**Comment by Istar-Eldritch** [comment]
Just to let know all the pinged reviewers. The main review I need is from @DennisSchwartz all the others are optional. You are free to check it out, if you want to block the deployment of this you can shout so it won't be merged without your review.

**Comment by Istar-Eldritch** [comment]
Fixed and unit tested the issue related with the spacing at the end of the expression you left from the review @DennisSchwartz

**Pull request merged**
